### ISSUE TITLE
[Fatal] [JDASocket]: Encountered an exception

### ISSUE THREAD

**Issue by Art3miss** [Fabricio20/DiscordSelfBot#5]
[12:52:17] [Info] [JDAAudioManager]: Audio System successfully setup!
[12:52:23] [Info] [JDA]: JDA starting...
[12:52:51] [Info] [JDA]: Login Successful!
[12:52:53] [Info] [JDASocket]: Connected to WebSocket
[12:53:35] [Fatal] [JDASocket]: Encountered an exception:
java.lang.NullPointerException
        at net.dv8tion.jda.handle.EntityBuilder.lambda$createGuildMemberPass$31(
EntityBuilder.java:254)
        at java.util.TimSort.countRunAndMakeAscending(Unknown Source)
        at java.util.TimSort.sort(Unknown Source)
        at java.util.Arrays.sort(Unknown Source)
        at java.util.ArrayList.sort(Unknown Source)
        at java.util.Collections.sort(Unknown Source)
        at net.dv8tion.jda.handle.EntityBuilder.createGuildMemberPass(EntityBuil
der.java:254)
        at net.dv8tion.jda.handle.EntityBuilder.createGuildFirstPass(EntityBuild
er.java:96)
        at net.dv8tion.jda.handle.ReadyHandler.handleInternally(ReadyHandler.jav
a:88)
        at net.dv8tion.jda.handle.SocketHandler.handle(SocketHandler.java:36)
        at net.dv8tion.jda.requests.WebSocketClient.handleEvent(WebSocketClient.
java:402)
        at net.dv8tion.jda.requests.WebSocketClient.onTextMessage(WebSocketClien
t.java:263)
        at net.dv8tion.jda.requests.WebSocketClient.onBinaryMessage(WebSocketCli
ent.java:520)
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(List
enerManager.java:368)
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(Readin
gThread.java:243)
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingT
hread.java:937)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.
java:696)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:10
2)
        at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:61)

**Comment by Fabricio20** [comment]
Expected, this has not been updated since like 4+ months ago, going to fix it this weekend.
